name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.3'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install allure-pytest
      # Install Allure commandline tool
    - name: Install Allure commandline
      run: |
        curl -s https://api.github.com/repos/allure-framework/allure2/releases/latest | jq -r .assets[0].browser_download_url | wget -i - -O allure.tgz
        tar -zxvf allure.tgz
        sudo mv allure-*/bin/allure /usr/local/bin/allure
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Run your tests
      run: pytest --tracing=retain-on-failure --alluredir=allure-results
          # Generate Allure Report
    - name: Generate Allure Report
      run: |
          allure serve allure-results

      # Upload Allure results as an artifact
    - name: Upload Allure Report as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-results
        
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-traces
        path: test-results/
