name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.3'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-html
        
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Run your tests
      run: pytest -s -v --disable-warnings --html=report.html

      # Upload the HTML report as an artifact
    - name: Upload HTML Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: pytest-html-report  # Name of the artifact
        path: report.html         # Path to the generated HTML report

      # Upload the assets folder as an artifact
    - name: Upload Assets Folder as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: pytest-html-assets
        path: assets  # Path to the assets folder
